project_id = "mfuvdsrtppoqojfrisii"

[functions.telegram-bot]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.create-product-payment]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.campaign-dispatch]
verify_jwt = true

[functions.funnel-webhook]
verify_jwt = false

[functions.wpp-api]
verify_jwt = true

[functions.wpp-webhook]
verify_jwt = false

[functions.mercadopago-oauth]
verify_jwt = true

[functions.mercadopago-callback]
verify_jwt = false

[functions.mercadopago-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.utmify-track]
verify_jwt = false
