project_id = "mfuvdsrtppoqojfrisii"

[functions.telegram-bot]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.campaign-dispatch]
verify_jwt = true

[functions.funnel-webhook]
verify_jwt = false
